import type { AICommandPreset } from '../types';

export const BUILTIN_AI_COMMANDS: AICommandPreset[] = [
  {
    id: 'polish_selection',
    code: 'polish_selection',
    name: '润色选区',
    description: '让选中文本更清楚、自然、顺畅',
    iconText: '润',
    agentIds: ['writing_assistant'],
    userPromptTemplate: '请润色下面选中的 Markdown 文本。只返回修改后的文本，不要解释修改原因。',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 10,
  },
  {
    id: 'expand_selection',
    code: 'expand_selection',
    name: '扩写段落',
    description: '在保留原意的基础上补充细节',
    iconText: '扩',
    agentIds: ['writing_assistant'],
    userPromptTemplate: '请扩写选中的段落，保持 Markdown 结构，输出可直接插入文档的内容。',
    resultMode: 'markdown',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 20,
  },
  {
    id: 'block_polish',
    code: 'block_polish',
    name: '润色当前块',
    description: '只处理当前选中的块',
    iconText: '块',
    agentIds: ['writing_assistant'],
    userPromptTemplate: '请润色当前选中的 Markdown 块。只返回修改后的块内容，不要解释。',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 22,
  },
  {
    id: 'block_expand',
    code: 'block_expand',
    name: '扩写当前块',
    description: '基于当前块补充细节',
    iconText: '扩',
    agentIds: ['writing_assistant'],
    userPromptTemplate: '请扩写当前选中的 Markdown 块，保留 Markdown 结构，只返回扩写后的块内容。',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 24,
  },
  {
    id: 'block_shorten',
    code: 'block_shorten',
    name: '缩短当前块',
    description: '压缩表达但保留核心意思',
    iconText: '短',
    agentIds: ['writing_assistant'],
    userPromptTemplate: '请缩短当前选中的 Markdown 块，保留核心意思和 Markdown 结构，只返回缩短后的块内容。',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 26,
  },
  {
    id: 'block_convert_to_list',
    code: 'block_convert_to_list',
    name: '当前块转列表',
    description: '把当前块改写为 Markdown 列表',
    iconText: '列',
    agentIds: ['writing_assistant', 'markdown_format_assistant'],
    userPromptTemplate: '请把当前选中的 Markdown 块改写为清晰的 Markdown 列表。只返回列表内容，不要解释。',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 28,
  },
  {
    id: 'block_generate_next',
    code: 'block_generate_next',
    name: '生成下一个块',
    description: '基于当前块续写一个新块',
    iconText: '续',
    agentIds: ['writing_assistant', 'tech_doc_assistant'],
    userPromptTemplate: '请基于当前选中的 Markdown 块和上下文，生成一个适合插入到当前块下方的新 Markdown 块。只返回新块内容。',
    resultMode: 'markdown',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 29,
  },
  {
    id: 'summarize_document',
    code: 'summarize_document',
    name: '生成摘要',
    description: '提炼当前文档重点',
    iconText: '摘',
    agentIds: ['writing_assistant', 'tech_doc_assistant'],
    userPromptTemplate: '请为当前 Markdown 文档生成结构化摘要，使用 Markdown 格式。',
    resultMode: 'markdown',
    contextStrategy: 'current_document',
    enabled: true,
    sortOrder: 30,
  },
  {
    id: 'translate_to_zh',
    code: 'translate_to_zh',
    name: '翻译成中文',
    description: '把选中文本翻译成中文',
    iconText: '中',
    agentIds: ['translator_assistant'],
    userPromptTemplate: '请把选中的 Markdown 文本翻译成中文。保留 Markdown 结构，只返回译文。',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 40,
  },
  {
    id: 'translate_to_en',
    code: 'translate_to_en',
    name: '翻译成英文',
    description: '把选中文本翻译成英文',
    iconText: 'EN',
    agentIds: ['translator_assistant'],
    userPromptTemplate: 'Please translate the selected Markdown text into English. Preserve the Markdown structure and return only the translation.',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 50,
  },
  {
    id: 'generate_readme',
    code: 'generate_readme',
    name: '生成 README',
    description: '基于当前内容生成 README 草稿',
    iconText: 'R',
    agentIds: ['tech_doc_assistant'],
    userPromptTemplate: '请基于当前文档内容生成一份 README.md 草稿，包含简介、安装、使用、配置和常见问题。',
    resultMode: 'markdown',
    contextStrategy: 'current_document',
    enabled: true,
    sortOrder: 60,
  },
  {
    id: 'fix_heading_level',
    code: 'fix_heading_level',
    name: '修复标题层级',
    description: '整理标题层级和列表结构',
    iconText: '#',
    agentIds: ['markdown_format_assistant'],
    userPromptTemplate: '请修复选中 Markdown 的标题层级和列表结构。只返回修复后的 Markdown。',
    resultMode: 'diff',
    contextStrategy: 'selection_with_cursor',
    enabled: true,
    sortOrder: 70,
  },
  {
    id: 'convert_to_md_table',
    code: 'convert_to_md_table',
    name: '转 Markdown 表格',
    description: '把选中内容整理成 Markdown 表格',
    iconText: '表',
    agentIds: ['markdown_format_assistant'],
    userPromptTemplate: '请把选中内容整理为标准 Markdown 表格。只返回表格。',
    resultMode: 'table',
    contextStrategy: 'selection_only',
    enabled: true,
    sortOrder: 80,
  },
  {
    id: 'extract_todos',
    code: 'extract_todos',
    name: '提取待办',
    description: '从当前内容提取任务列表',
    iconText: '办',
    agentIds: ['writing_assistant', 'tech_doc_assistant'],
    userPromptTemplate: '请从上下文中提取待办事项，返回 Markdown 任务列表：- [ ] xxx。',
    resultMode: 'todo',
    contextStrategy: 'current_document',
    enabled: true,
    sortOrder: 90,
  },
];
